DROP DATABASE IF EXISTS DB02;
CREATE DATABASE IF NOT EXISTS DB02;
USE DB02;

DROP TABLE IF EXISTS CHI_TIET_HOA_DON;
DROP TABLE IF EXISTS HOA_DON;
DROP TABLE IF EXISTS KHACH_HANG;
DROP TABLE IF EXISTS NHAN_VIEN;
DROP TABLE IF EXISTS MAT_HANG;
DROP TABLE IF EXISTS NHOM_MAT_HANG;

CREATE TABLE NHOM_MAT_HANG (
  MA_NHOM CHAR(5) PRIMARY KEY,
  TEN_NHOM VARCHAR(50) NOT NULL
);

CREATE TABLE MAT_HANG (
  MA_MH CHAR(10) PRIMARY KEY,
  TEN_MH VARCHAR(50) NOT NULL,
  GIA_MH INTEGER NOT NULL,
  SL_TONKHO INTEGER NOT NULL DEFAULT 0,
  MA_NHOM CHAR(5) NOT NULL,
  CONSTRAINT FK_MAT_HANG_NHOM FOREIGN KEY (MA_NHOM) REFERENCES NHOM_MAT_HANG(MA_NHOM)
);

CREATE TABLE NHAN_VIEN (
  MA_NV CHAR(5) PRIMARY KEY,
  TEN_NV VARCHAR(50) NOT NULL,
  CHUC_VU VARCHAR(30) NOT NULL,
  SDT_NV CHAR(10) NOT NULL
);

CREATE TABLE KHACH_HANG (
  MA_KH CHAR(5) PRIMARY KEY,
  TEN_KH VARCHAR(50) NOT NULL,
  SDT_KH CHAR(10) NOT NULL,
  DIA_CHI VARCHAR(100) NOT NULL
);

CREATE TABLE HOA_DON (
  MA_HD CHAR(10) PRIMARY KEY,
  NGAY_LAP DATE NOT NULL,
  MA_NV CHAR(5) NOT NULL,
  MA_KH CHAR(5) NOT NULL,
  CONSTRAINT FK_HOA_DON_NV FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV),
  CONSTRAINT FK_HOA_DON_KH FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH)
);

CREATE TABLE CHI_TIET_HOA_DON (
  MA_HD CHAR(10) NOT NULL,
  MA_MH CHAR(10) NOT NULL,
  SO_LUONG INTEGER NOT NULL,
  PRIMARY KEY (MA_HD, MA_MH),
  CONSTRAINT FK_CTHD_HD FOREIGN KEY (MA_HD) REFERENCES HOA_DON(MA_HD),
  CONSTRAINT FK_CTHD_MH FOREIGN KEY (MA_MH) REFERENCES MAT_HANG(MA_MH)
);